site_name: SamplePage
repo_url: https://github.com/fereria/mkdocs_sample
site_url: https://fereria.github.io/mkdocs_sample/
site_author: SampleName

theme:
  favicon: "favicon.ico"
  custom_dir: "theme"
  language: ja
  name: material
  palette:
    accent: Green
    primary: Green
  features:
    - navigation.tabs
    - navigation.expand
  icon:
    repo: fontawesome/brands/github

# TwitterやGithubのリンクを指定できるアイコンはサイト右下に表示される
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fereria
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fereria
    - icon: fontawesome/solid/bookmark
      link: https://zenn.dev/remiria

extra_css:
  - https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
  - stylesheets/extra.css
  - https://unpkg.com/mermaid@8.0.0/dist/mermaid.css

extra_javascript:
  - javascripts/extra.js
  - https://unpkg.com/mermaid@8.0.0/dist/mermaid.min.js

# Googleアナリティクスを使いたい場合。
# google_analytics:
#   - UA-#######
#   - auto

plugins:
  - drawio-exporter:
      cache_dir: "drawio-exporter"
      drawio_executable: null
      drawio_args: ["--no-sandbox"]
      format: svg
      embed_format: "{img_open}{img_src}{img_close}"
      sources: "*.drawio"
  - git-revision-date-localized:
      type: iso_datetime
  - search:
      lang:
        - en
        - ja
  - awesome-pages
  - macros
  - mdoctag:
      tagpage_dir: "tags"
      data_filename: "tags.json"

markdown_extensions:
  - hbfm.quote_uri_hash
  - hbfm.inline_coloring
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - markdown.extensions.nl2br
  - fontawesome_markdown
  - def_list
  - admonition
  - meta
  - footnotes
  - pymdownx.critic
  - markdown_blockdiag:
      format: svg
  - toc:
      permalink: "¶"
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.highlight:
      linenums: true
